
/*
 * This was manually created, not generated by OpenAPI
 *
 */
export type WorkflowStateEnum = 'INITIAL' | 'PUBLISHED' | 'COMMENT_OPEN' | 'COMMENT_CLOSED' | 'FINALIZED' |
  'EXPIRED';

export const WorkflowStateEnum = {
  INITIAL: 'INITIAL' as WorkflowStateEnum,
  PUBLISHED: 'PUBLISHED' as WorkflowStateEnum,
  COMMENT_OPEN: 'COMMENT_OPEN' as WorkflowStateEnum,
  COMMENT_CLOSED: 'COMMENT_CLOSED' as WorkflowStateEnum,
  FINALIZED: 'FINALIZED' as WorkflowStateEnum,
  EXPIRED: 'EXPIRED' as WorkflowStateEnum
};
